# Generated by Django 5.1.7 on 2025-05-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('entry_operator', 'Entry Operator'), ('accountant', 'Accountant'), ('order_manager', 'Order Manager'), ('product_manager', 'Product Manager'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
